### ISSUE TITLE
Failure Code 503

### ISSUE THREAD

**Issue by sven-s-ter** [iobroker-community-adapters/ioBroker.rainbird#17]
Several failures with V0.2.3. 

Actual jscontroler 4.0.23, updated iobroker. Node 16.17.0 Npm 8.15.0. 

Rainbird Module ESP-ME3 7 Zones. 

Following failures:

Failure in states -> Shows irrigation true (which is not)

Run zones are not working.

Failures in Protocol:

![image](https://user-images.githubusercontent.com/71233096/185800185-53e5d343-309b-4cb3-a46a-1aad37ed5763.jpeg)

Thx!

**Comment by mcm1957** [comment]
issue seems to be outdated.
If problem still exists with current 2.0.x please open a new isseu and attach a log with loglevel set to DEBUG
