### ISSUE TITLE
Pleae modify :-(

### ISSUE THREAD

**Issue by smarteshome2020** [iobroker-community-adapters/ioBroker.rainbird#19]
Hi, im using iobroker upto date with NPM V 8.19.3 and Nodejs V16.19.0.

It is not possibe to install the adapter and i recieved the following error.

install StrathCole/ioBroker.rainbird#0caa24dcbb11024865ff9161c6f6bb5e6db6a9ce
NPM version: 8.19.3
Installing StrathCole/ioBroker.rainbird#0caa24dcbb11024865ff9161c6f6bb5e6db6a9ce... (System call)
npm WARN old lockfile npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.npm WARN old lockfile npm WARN old lockfile This is a one-time fix-up, please be patient...npm WARN old lockfile

**Comment by mcm1957** [comment]
outdated - should work with 1.0.1
