### ISSUE TITLE
Migrate @strathcole/iob-lib

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.rainbird#27]
Migrate @strathcole/iob-lib to local repository

**Comment by mcm1957** [comment]
The repository @strathcole/iob-lib contains ioBroker spezific code and is no longer maintained. ioBroker specific code should be located at the adapter or at least at a repositories that is accessable by the same persons the adapter itself.

**Comment by Feuer-sturm** [comment]
I will try if I can migrate it.

**Comment by mcm1957** [comment]
Check if you can simply move the script to the lib directory and adapt the require statement at main.
I think this could work as a first step.

**Comment by Feuer-sturm** [comment]
@mcm1957 I can try to understande what the code section is doing and if it is correct to switch from warning to debug

**Comment by Feuer-sturm** [comment]
@mcm1957 can you please support me with the PR?
eslint check has two errors for iob-lib.js
```
Error:   109:42  error    'obj' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
Error:   111:45  error    'err' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
```

What is the easiest way in this case for migrating the iob-lib without changing functionality? Is it ok, as sugessted to rename them to _obj and _err?

**Comment by mcm1957** [comment]
_err, _obj should satisfy eslint.

**Comment by Feuer-sturm** [comment]
@mcm1957 Thanks. PR ist ready.

**Comment by Feuer-sturm** [comment]
PR is merged. Issue can be closed @mcm1957

**Comment by mcm1957** [comment]
done at 2.0.2

**Comment by mcm1957** [comment]
> PR is merged. Issue can be closed @mcm1957

I'll just wait for the realease to be deployed and for some feedback that it works :-)
