### ISSUE TITLE
Not all Parameters visible in iobroker when rainbird is in another subnet

### ISSUE THREAD

**Issue by boos87** [iobroker-community-adapters/ioBroker.rainbird#9]
Hello everyone,

i have tested the rainbird adapter. When the rainbird wifi is in the same wifi/network like the raspberry pi, the adapter works perfect. Rainbird and raspberry are in the network like 192.168.0.X with subnet 255.255.255.0. Everything is working right.

I have another router in the garage, which is connect to the same network 192.168.0.X, but there is a adressrange for the devices with 192.168.1.X. So the rainbird wifi ist addressed 192.168.1.X and i can´t see all parameters from the rainbird in iobroker. The adapter isn´t working.

Can anybody help me, please??????

**Comment by mcm1957** [comment]
issue seems to be outdated.
If problem still exists with current 2.0.x please open a new isseu and attach a log with loglevel set to DEBUG
